server:
  port: 8081
  tomcat:
    relaxed-path-chars:
      - "^"
      - "+"
    relaxed-query-chars:
      - "^"
      - "+"
application:
  config:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
