version: "3"

services:
  json-generator-service:
    build:
      context: ./JsonGenerator

    ports:
      - "8080:8080"



  csv-converter-service:
    build:
      context: ./CsvConverter

    ports:
      - "8081:8081"
    environment:
      - APPLICATION_CONFIG_HOSTNAME=json-generator-service




  raport-service:
    build:
      context: ./RaportService

    ports:
      - "8082:8082"
    environment:
      - APPLICATION_CONFIG_HOSTNAME=csv-converter-service

