server:
    port: 8082
    tomcat:
        relaxed-path-chars:
            - "^"
            - "+"
        relaxed-query-chars:
            - "^"
            - "+"
application:
  config:
    hostname: localhost
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML


