server:
    port: 8082
    tomcat:
        relaxed-path-chars:
            - "^"
            - "+"
        relaxed-query-chars:
            - "^"
            - "+"
application:
    config:
        json-url: http://localhost:8081
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML


