server:
  port: 8081

application:
  config:
    json-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: metrics
  endpoint:
    metrics:
      enabled: true
